name: Deploy Docs to Prodction Top Mezon AI

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/deploy-prod-docs.yml'
jobs:
  deploy:
    runs-on: top-prod
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Node Module
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json,**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Build FE & Deploy
      run: |
        cd docs/
        yarn
        yarn build
        cp -r build/* /var/www/top-mezon-ai-docs/
