name: Deploy BE to Prodction Top Mezon AI

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-prod-be.yml'

jobs:
  deploy:
    runs-on: top-prod
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Env-Config
      run: |
        cd backend/
        echo '${{ secrets.ENV_PROD_BE }}' > .env.prod

    - name: Build BE & Deploy
      run: |
        export NVM_DIR=~/.nvm
        source ~/.nvm/nvm.sh
        cd backend/
        nvm use 22
        yarn
        yarn build
        cp -r . /var/www/top-mezon-ai-be/
        pm2 restart mezontop